import {test} from 'node:test';import assert from 'node:assert/strict';import {mkdtempSync,writeFileSync,readFileSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';import {createHash} from 'node:crypto';
import {canonical} from './stage0-T-after-O-20261008T183600Z-contract.mjs';
const root=mkdtempSync(join(tmpdir(),'hm-T-commit-'));process.env.ACCEPTANCE_STATE_DIR=root;process.env.ACCEPTANCE_STAGE0_MODE='commit';let network=0;globalThis.fetch=async()=>{network++;return Response.json({mutateOperationResponses:[]});};
const prefix='acceptance-stage0-T-live-commit-20261008T185500Z',c={service_token:'test-only-key',preview:{preview_token:'test-only-preview'}},ops=[{campaignOperation:{create:{resourceName:'customers/8590146099/campaigns/-2',name:'fixture',status:'PAUSED'}}}],body={mutateOperations:ops,validateOnly:false,partialFailure:false};
const arm={customer_id:'8590146099',test_account:true,login_customer_id:'4378327049',hierarchy:true,preview_id:'2c770f7a-e205-4e23-a572-193ade55c4db',approved:true,session_valid:true,approval_audit:true,immutable:true,operation_count:26,body_digest:createHash('sha256').update(canonical(body)).digest('hex'),expires_at:new Date(Date.now()+600000).toISOString(),verified_at:new Date().toISOString()};
writeFileSync(join(root,'acceptance-stage0-T-after-O-20261008T183600Z-protected-context.json'),JSON.stringify(c));writeFileSync(join(root,'acceptance-stage0-readiness-v4-20261008-prepared-plan.json'),JSON.stringify({provider_operations:ops}));
const save=v=>writeFileSync(join(root,prefix+'-arm.json'),JSON.stringify(v));save(arm);
Object.assign(process.env,{V2_PREVIEW_ONLY:'false',V2_CONFIRMED_WRITE_ENABLED:'true',PROVIDER_GOOGLE_ADS_WRITE_ENABLED:'true',GOOGLE_ADS_WRITE_ACCOUNT_ALLOWLIST:'8590146099',PUBLIC_MCP_WRITE_SCOPE_ENABLED:'false',PUBLIC_MCP_CONTROLLED_WRITE_ENABLED:'false'});
const g=await import('./T-live-commit-guard.mjs'),endpoint='https://googleads.googleapis.com/v24/customers/8590146099/googleAds:mutate',req=b=>({method:'POST',headers:{'login-customer-id':'4378327049'},body:JSON.stringify(b)}),rpc=(n,a)=>({method:'POST',headers:{authorization:'Bearer '+c.service_token},body:JSON.stringify({jsonrpc:'2.0',method:'tools/call',params:{name:n,arguments:a}})});
test('only exact immutable commit RPC; no approval/newpreview/replacement',()=>{assert.equal(g.validateRequest('http://127.0.0.1:4000/mcp',rpc('commit_preview',{preview_token:c.preview.preview_token})),'commit');for(const[n,a]of [['confirm_preview',{}],['create_campaign_from_brief',{}],['commit_preview',{preview_token:'other'}],['commit_preview',{preview_token:c.preview.preview_token,status:'ENABLED'}]])assert.throws(()=>g.validateRequest('http://127.0.0.1:4000/mcp',rpc(n,a)));});
test('atomic exact stored26 operation plan; partialFailure/validate_only/budget cannot change',()=>{assert.equal(g.validateRequest(endpoint,req(body)),'write');for(const delta of [{partialFailure:true},{validateOnly:true},{mutateOperations:[]},{mutateOperations:[{campaignOperation:{create:{name:'different'}}}]}])assert.throws(()=>g.validateRequest(endpoint,req({...body,...delta})));assert.equal(network,0);});
test('MCC and all foreign accounts denied',()=>{for(const id of ['4378327049','9999999999'])assert.throws(()=>g.validateRequest(endpoint.replace('8590146099',id),req(body)));assert.throws(()=>g.validateRequest(endpoint,{...req(body),headers:{'login-customer-id':'9999999999'}}));});
test('approval, proof, expired session and exact allowlist fail closed',()=>{for(const delta of [{test_account:false},{hierarchy:false},{approved:false},{session_valid:false},{approval_audit:false},{immutable:false},{preview_id:'other'},{expires_at:new Date(0).toISOString()},{verified_at:new Date(0).toISOString()}]){save({...arm,...delta});assert.throws(()=>g.validateRequest(endpoint,req(body)));}save(arm);process.env.GOOGLE_ADS_WRITE_ACCOUNT_ALLOWLIST='8590146099,4378327049';assert.throws(()=>g.validateRequest(endpoint,req(body)));process.env.GOOGLE_ADS_WRITE_ACCOUNT_ALLOWLIST='8590146099';});
test('all resource rereads and26 audits required; fixture unchanged; no retry',()=>{const s=readFileSync(new URL('./T-live-commit.mjs',import.meta.url),'utf8');for(const v of ['T_commit_unverified_stop_no_retry','T_independent_reread_unverified','T_original_fixture_changed','success.length!==26','verifyStage0Mutation(plan','fingerprint(stored)!==previewEvidence.immutable_preview_fingerprint'])assert.ok(s.includes(v));assert.equal(network,0);});
test('native mutation guarded at most once',async()=>{await fetch(endpoint,req(body));assert.equal(network,1);await assert.rejects(fetch(endpoint,req(body)));assert.equal(network,1);});

